name: CI
on: [push]
jobs:
  eslint:
    name: ShopApp
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install packages
        run: npm ci
      - name: Run ESlint
        run: npm run lint